[package]
name = "axum-config"
version = "0.1.0"
edition = "2024"
authors = ["Luciano Revillod <lrevillod2022@alu.uct.cl>"]
license = "MIT"
description = "Proc macros for axum-config"
repository = "https://github.com/MrRevillod/axum-config"
keywords = ["axum", "config", "toml", "environment"]
categories = ["config", "web-programming"]

[dependencies]
axum = "0.8.8"
axum-config-macros = { version = "0.1.0", path = "axum-config-macros" }
regex-lite = "0.1.8"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.17"
toml = "0.9.10"
tracing = "0.1.44"

[dev-dependencies]
tokio = { version = "1.40", features = ["full"] }
tempfile = "3.14"
